### ISSUE TITLE
Training on bigrams?

### ISSUE THREAD

**Issue by bdlacree** [bmschmidt/wordVectors#11]
Hey! Wonderful package. Is there currently support for training the word2vec model on bigrams as well as unigrams? I've had some nice success using bigrams via gensim, and was wondering if I'm missing the way to include that here.

Thanks! Again, great work.

**Comment by bmschmidt** [comment]
No built-in support: this just wraps the word2vec C code here, and that only handles whitespace tokenization. So if you have text (from gensim or elsewhere) that already is split by underscores, it'll handle it; but there isn't (and isn't likely to be) a switch to flip. I will say that In cases where the Google word2vec code doesn't work (eg, when a streaming implementation is useful) I just use gensim to build the model in python and then load it into R for analysis because I prefer R syntax.

**Comment by mukul13** [comment]
Hello,
         I am also trying to write a R wrapper to google word2vec code (to cover all Google's word2vec c codes) similar to tmcn.word2vec. Google's word2vec code provides a word2phrase function which converts text data into unigrams and bigrams. I have written a R wrapper for it ([Github repo link](https://github.com/mukul13/rword2vec)). Would love to hear your feedback if possible.
Thanks.

**Comment by bmschmidt** [comment]
Closing this because thanks to @mukul13 , it's in here now too.
