### ISSUE TITLE
Delimiter of text context

### ISSUE THREAD

**Issue by sinacek** [bmschmidt/wordVectors#23]
Hi,
thanks for the library. I would like ask you if it's possible defined some delimited for sliding window. I want for example add each sentence on new line and as a context for each of word use words on same row.

Example:
I have a dream.
Cat eats a hotdog.

So I wold like have context of dream just {I, have, a} not Cat...

It's possible to do that?

**Comment by bmschmidt** [comment]
Yes, it is by default. Just the way you have laid it out will (according to Mikolov on Google Groups) separate out the lines so that "dream" and "Cat" do not appear in the same window as each other.

https://groups.google.com/forum/#!searchin/word2vec-toolkit/line$20break%7Csort:relevance/word2vec-toolkit/2elkT3cOMqo/DL_CsF1p8H8J
